version: "3.8"

services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: banking-mock-server
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - "--global-response-templating"
